trigger: none

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

steps:
  - task: Bash@3
    name: GenerateExportVars
    displayName: ðŸ”§ Generate export-vars.sh
    inputs:
      targetType: 'inline'
      script: |
        echo "ðŸ”§ Generating export-vars.sh..."
        cat > export-vars.sh <<EOF
#!/bin/bash
export ORG="${ORG}"
export PROJECT="${PROJECT}"
export AZURE_DEVOPS_PAT="${AZURE_DEVOPS_PAT}"
export TRACKCOUNT=1
export track1_name="${track1_name}"
export track1_type="${track1_type}"
export track1_appid="${track1_appid}"
export track1_apptype="${track1_apptype}"
EOF
        chmod +x export-vars.sh
        echo "âœ… export-vars.sh created"

  - task: Bash@3
    displayName: ðŸ“œ Make create-multi-env-vgs.sh executable
    inputs:
      targetType: 'inline'
      script: |
        chmod +x ./create-multi-env-vgs.sh

  - task: Bash@3
    name: CreateVariableGroups
    displayName: ðŸš€ Create Env Variable Groups
    inputs:
      targetType: 'inline'
      script: |
        source ./export-vars.sh

        echo "ðŸ” Environments to process: ${{ join(',', parameters.environments) }}"

        trackname="${track1_name}"
        tracktype="${track1_type}"
        appid="${track1_appid}"
        apptype="${track1_apptype}"

        echo "ðŸ§© Track 1: name=$trackname, type=$tracktype, appid=$appid, apptype=$apptype"

        for env in "${{ parameters.environments[@] }}"; do
          echo "âž¡ï¸ Creating variable group for $env - $appid - $trackname"
          ./create-multi-env-vgs.sh "$env" "$appid" "$trackname" "$tracktype" "$apptype"
        done
