trigger: none

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

steps:
  - script: |
      echo "🔧 Generating export-vars.sh..."
      echo '#!/bin/bash' > export-vars.sh

      echo "export ORG=\"$(ORG)\"" >> export-vars.sh
      echo "export PROJECT=\"$(PROJECT)\"" >> export-vars.sh
      echo "export AZURE_DEVOPS_PAT=\"$(AZURE_DEVOPS_PAT)\"" >> export-vars.sh
      echo "export TRACKCOUNT=$(TRACKCOUNT)" >> export-vars.sh

      for i in {1..10}; do
        echo "export track${i}_name=\"$(eval echo \${{ variables['track${i}_name'] }})\"" >> export-vars.sh
        echo "export track${i}_type=\"$(eval echo \${{ variables['track${i}_type'] }})\"" >> export-vars.sh
        echo "export track${i}_appid=\"$(eval echo \${{ variables['track${i}_appid'] }})\"" >> export-vars.sh
        echo "export track${i}_apptype=\"$(eval echo \${{ variables['track${i}_apptype'] }})\"" >> export-vars.sh
      done

      chmod +x export-vars.sh
      echo "✅ export-vars.sh content:"
      cat export-vars.sh
    displayName: '🔧 Build export-vars.sh dynamically'

  - script: |
      chmod +x ./process-vg-create-vg-source.sh
      ./process-vg-create-vg-source.sh "${{ join(',', parameters.environments) }}"
    displayName: '🚀 Create all env variable groups'
