trigger: none

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

steps:
  # Task 1: Install jq and set permissions
  - task: Bash@3 # 2 spaces indent
    displayName: "⚙️ Install jq and set permissions" # 4 spaces indent
    inputs: # 4 spaces indent
      targetType: 'inline' # 6 spaces indent
      script: | # 6 spaces indent
        # All lines of the script content must be indented 2 spaces further than 'script: |' (i.e., 8 spaces total)
        echo "Installing jq for JSON processing..."
        sudo apt-get update && sudo apt-get install -y jq
        echo "jq installed."
        
        echo "Making create-multi-env-vgs.sh executable..."
        chmod +x ./create-multi-env-vgs.sh
        echo "Permissions set."

  # Task 2: Create Variable Groups
  - task: Bash@3 # 2 spaces indent
    displayName: "🚀 Create Variable Groups" # 4 spaces indent
    inputs: # 4 spaces indent
      targetType: 'inline' # 6 spaces indent
      # THIS IS THE LINE (OR AROUND IT) THAT IS CAUSING YOUR ERROR.
      # Ensure 'env:' is AT THE SAME INDENTATION LEVEL (6 spaces) as 'targetType:' and 'script:'
      env: # <-- LINE 40 (approximately). MUST have exactly 6 spaces before 'env:'.
        ORG: $(ORG) # 8 spaces indent
        PROJECT: $(PROJECT) # 8 spaces indent
        AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT) # 8 spaces indent
        TRACK1_NAME: $(track1_name) # 8 spaces indent
        TRACK1_TYPE: $(track1_type) # 8 spaces indent
        TRACK1_APPID: $(track1_appid) # 8 spaces indent
        TRACK1_APPTYPE: $(track1_apptype) # 8 spaces indent
      script: | # 6 spaces indent
        # All lines of the script content must be indented 2 spaces further than 'script: |' (i.e., 8 spaces total)
        echo "Starting Variable Group Creation process..."

        ORG="${ORG}"
        PROJECT="${PROJECT}"
        AZURE_DEVOPS_PAT="${AZURE_DEVOPS_PAT}"

        trackname="${TRACK1_NAME}"
        tracktype="${TRACK1_TYPE}"
        appid="${TRACK1_APPID}"
        apptype="${TRACK1_APPTYPE}"

        if [[ -z "$trackname" || -z "$tracktype" || -z "$appid" || -z "$apptype" ]]; then
          echo "❌ ERROR: Missing track1 input from variable group."
          echo "Please ensure 'track1_name', 'track1_type', 'track1_appid', 'track1_apptype' are set in 'vg-create-vg-source'."
          exit 1
        fi

        echo "🧩 Track 1 details: name=$trackname, type=$tracktype, appid=$appid, apptype=$aptype"
        echo "Azure DevOps Org: $ORG, Project: $PROJECT"

        environments_str="${{ join(' ', parameters.environments) }}"
        IFS=' ' read -r -a environments_array <<< "$environments_str"

        echo "🔁 Environments to process: ${environments_array[@]}"

        for env in "${environments_array[@]}"; do
          echo "➡️ Attempting to create variable group for environment: $env"
          ./create-multi-env-vgs.sh "$env" "$appid" "$trackname" "$tracktype" "$apptype" "$ORG" "$PROJECT" "$AZURE_DEVOPS_PAT"
        done

        echo "Variable Group Creation process completed."
