trigger: none

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

parameters:
  - name: environments
    type: object
    default:
      - DEV
      - SIT
      - UAT
      - PT
      - PROD
      - DR

steps:
  - task: Bash@3
    displayName: "🔧 Generate export-vars.sh"
    inputs:
      targetType: 'inline'
      script: |
        echo "🔧 Generating export-vars.sh..."
        cat <<EOF > export-vars.sh
#!/bin/bash
export ORG="${ORG}"
export PROJECT="${PROJECT}"
export AZURE_DEVOPS_PAT="${AZURE_DEVOPS_PAT}"
export TRACKCOUNT=1
export track1_name="${track1_name}"
export track1_type="${track1_type}"
export track1_appid="${track1_appid}"
export track1_apptype="${track1_apptype}"
EOF
        chmod +x export-vars.sh
        echo "✅ export-vars.sh created"

  - task: Bash@3
    displayName: "🔐 Make create-multi-env-vgs.sh Executable"
    inputs:
      targetType: 'inline'
      script: |
        chmod +x ./create-multi-env-vgs.sh

  - task: Bash@3
    displayName: "🚀 Create Variable Groups"
    inputs:
      targetType: 'inline'
      script: |
        source ./export-vars.sh

        echo "🔁 Environments to process: ${parameters.environments}"

        trackname="${track1_name}"
        tracktype="${track1_type}"
        appid="${track1_appid}"
        apptype="${track1_apptype}"

        if [[ -z "$trackname" || -z "$tracktype" || -z "$appid" || -z "$apptype" ]]; then
          echo "❌ ERROR: Missing input for track1"
          exit 1
        fi

        echo "🧩 Track 1: name=$trackname, type=$tracktype, appid=$appid, apptype=$apptype"

        for env in "${parameters.environments[@]}"; do
          echo "➡️ Creating variable group for $env - $appid - $trackname"
          ./create-multi-env-vgs.sh "$env" "$appid" "$trackname" "$tracktype" "$apptype"
        done
