trigger: none

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

steps:
  - script: |
      echo "🔧 Generating export-vars.sh..."

      echo '#!/bin/bash' > export-vars.sh
      echo "export ORG=\"$(ORG)\"" >> export-vars.sh
      echo "export PROJECT=\"$(PROJECT)\"" >> export-vars.sh
      echo "export AZURE_DEVOPS_PAT=\"$(AZURE_DEVOPS_PAT)\"" >> export-vars.sh
      echo "export TRACKCOUNT=$(TRACKCOUNT)" >> export-vars.sh
      echo "" >> export-vars.sh
      echo "# Dynamically export all trackN_* variables" >> export-vars.sh

      COUNT=$(TRACKCOUNT)
      for i in $(seq 1 $COUNT); do
        name_var="track${i}_name"
        type_var="track${i}_type"
        appid_var="track${i}_appid"
        apptype_var="track${i}_apptype"

        name_value="${!name_var}"
        type_value="${!type_var}"
        appid_value="${!appid_var}"
        apptype_value="${!apptype_var}"

        if [[ -z "$name_value" || -z "$type_value" || -z "$appid_value" || -z "$apptype_value" ]]; then
          echo "❌ ERROR: Missing variables for track$i"
          exit 1
        fi

        echo "export ${name_var}=\"${name_value}\"" >> export-vars.sh
        echo "export ${type_var}=\"${type_value}\"" >> export-vars.sh
        echo "export ${appid_var}=\"${appid_value}\"" >> export-vars.sh
        echo "export ${apptype_var}=\"${apptype_value}\"" >> export-vars.sh
        echo "" >> export-vars.sh
      done

      chmod +x export-vars.sh
      echo "✅ export-vars.sh created with:"
      cat export-vars.sh
    displayName: '🔧 Generate export-vars.sh from vg-create-vg-source'

  - script: |
      chmod +x export-vars.sh
      source ./export-vars.sh

      chmod +x ./process-vg-create-vg-source.sh
      ./process-vg-create-vg-source.sh "${{ join(',', parameters.environments) }}"
    displayName: '🚀 Process all Env-specific Variable Groups'
