trigger: none

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

steps:
  - checkout: self

  - task: Bash@3
    displayName: 'Set execute permission on scripts'
    inputs:
      targetType: inline
      script: |
        chmod +x ./process-vg-create-vg-source.sh
        chmod +x ./create-multi-env-vgs.sh

  - task: Bash@3
    displayName: 'Create Env-specific Variable Groups'
    inputs:
      targetType: filePath
      filePath: ./process-vg-create-vg-source.sh
    env:
      PARAM_ENVIRONMENTS: ${{ join(',', parameters.environments) }}
      ORG: $(ORG)
      PROJECT: $(PROJECT)
      AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)
      # Also exports all vg-create-vg-source values at runtime
