trigger: none

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

steps:
  - checkout: self

  - task: Bash@3
    displayName: 'Make scripts executable'
    inputs:
      targetType: inline
      script: |
        chmod +x ./process-vg-create-vg-source.sh
        chmod +x ./create-multi-env-vgs.sh

  - task: Bash@3
    displayName: 'Export dynamic track variables'
    name: exportTrackVars
    inputs:
      targetType: inline
      script: |
        echo "🧩 Exporting dynamic track variables..."
        printenv | grep '^track[0-9]_.*' >> export-vars.sh
        sed -i 's/^/export /' export-vars.sh
        cat export-vars.sh
        echo "✅ Export file generated."

  - task: Bash@3
    displayName: 'Run variable group creation'
    inputs:
      targetType: filePath
      filePath: ./process-vg-create-vg-source.sh
      arguments: ${{ join(',', parameters.environments) }}
    env:
      ORG: $(ORG)
      PROJECT: $(PROJECT)
      AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)
      TRACKCOUNT: $(trackcount)
    condition: succeeded()
