trigger: none

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

steps:
  - script: |
      echo "🔧 Generating dynamic export-vars.sh..."
      echo "#!/bin/bash" > export-vars.sh

      echo "export ORG=\"$(ORG)\"" >> export-vars.sh
      echo "export PROJECT=\"$(PROJECT)\"" >> export-vars.sh
      echo "export AZURE_DEVOPS_PAT=\"$(AZURE_DEVOPS_PAT)\"" >> export-vars.sh
      echo "export TRACKCOUNT=$(TRACKCOUNT)" >> export-vars.sh

      count=$(TRACKCOUNT)
      for ((i=1; i<=count; i++)); do
        for key in name type appid apptype; do
          var="track${i}_${key}"
          val="$(echo "${!var:-$(eval echo \${$var})}")"
          echo "export $var=\"${val}\"" >> export-vars.sh
        done
      done

      chmod +x export-vars.sh
      echo "✅ export-vars.sh generated:"
      cat export-vars.sh
    displayName: '🔧 Dynamically generate export-vars.sh'

  - script: |
      chmod +x ./process-vg-create-vg-source.sh
      ./process-vg-create-vg-source.sh "${{ join(',', parameters.environments) }}"
    displayName: '🚀 Process all envs and create variable groups'
