trigger: none

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

steps:
  - script: |
      chmod +x ./create-multi-env-vgs.sh

      echo "🔁 Environments to process:"
      environments="${{ join(',', parameters.environments) }}"
      IFS=',' read -ra ENV_LIST <<< "$environments"

      # Manually export all track variables
      export TRACKCOUNT=$(echo "$(TRACKCOUNT)")
      export track1_name="$(track1_name)"
      export track1_type="$(track1_type)"
      export track1_appid="$(track1_appid)"
      export track2_name="$(track2_name)"
      export track2_type="$(track2_type)"
      export track2_appid="$(track2_appid)"
      # Add more if TRACKCOUNT > 2

      echo "Found TRACKCOUNT=$TRACKCOUNT"

      for ((i=1; i<=${TRACKCOUNT}; i++)); do
        trackname=$(eval echo "\$track${i}_name")
        tracktype=$(eval echo "\$track${i}_type")
        appid=$(eval echo "\$track${i}_appid")

        echo "🧩 Track $i: name=$trackname, type=$tracktype, appid=$appid"

        for env in "${ENV_LIST[@]}"; do
          echo "➡️ Creating variable group for $env - $appid - $trackname"
          ./create-multi-env-vgs.sh "$env" "$appid" "$trackname" "$tracktype"
        done
      done
    displayName: 'Create Env-specific Variable Groups from vg-create-vg-source'
