trigger: none

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

parameters:
  - name: environments
    type: object
    default:
      - DEV
      - SIT
      - UAT
      - PT
      - PROD
      - DR

steps:
  - task: Bash@3
    name: GenerateExportVars
    displayName: 🔧 Generate export-vars.sh
    inputs:
      targetType: 'inline'
      script: |
        echo "🔧 Generating export-vars.sh..."

        echo '#!/bin/bash' > export-vars.sh
        echo "export ORG=\"${ORG}\"" >> export-vars.sh
        echo "export PROJECT=\"${PROJECT}\"" >> export-vars.sh
        echo "export AZURE_DEVOPS_PAT=\"${AZURE_DEVOPS_PAT}\"" >> export-vars.sh
        echo "export TRACKCOUNT=1" >> export-vars.sh
        echo "export track1_name=\"${track1_name}\"" >> export-vars.sh
        echo "export track1_type=\"${track1_type}\"" >> export-vars.sh
        echo "export track1_appid=\"${track1_appid}\"" >> export-vars.sh
        echo "export track1_apptype=\"${track1_apptype}\"" >> export-vars.sh

        chmod +x export-vars.sh
        echo "✅ export-vars.sh created"

  - task: Bash@3
    name: CreateVariableGroups
    displayName: 🚀 Create Env Variable Groups
    inputs:
      targetType: 'inline'
      script: |
        source ./export-vars.sh

        echo "🔁 Environments to process: ${{ join(',', parameters.environments) }}"
        ENV_LIST="${{ join(',', parameters.environments) }}"
        IFS=',' read -ra ENV_ARRAY <<< "$ENV_LIST"

        trackname="${track1_name}"
        tracktype="${track1_type}"
        appid="${track1_appid}"
        apptype="${track1_apptype}"

        echo "🧩 Track 1: name=$trackname, type=$tracktype, appid=$appid, apptype=$apptype"

        for env in "${ENV_ARRAY[@]}"; do
          echo "➡️ Creating variable group for $env - $appid - $trackname"
          ./create-multi-env-vgs.sh "$env" "$appid" "$trackname" "$tracktype" "$apptype"
        done
