trigger: none

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

steps:
  - task: Bash@3
    name: GenerateExportVars
    displayName: "🔧 Generate export-vars.sh"
    inputs:
      targetType: 'inline'
      script: |
        echo "🔧 Generating export-vars.sh..."
        cat > export-vars.sh <<EOF
#!/bin/bash
export ORG="${ORG}"
export PROJECT="${PROJECT}"
export AZURE_DEVOPS_PAT="${AZURE_DEVOPS_PAT}"
export TRACKCOUNT=1
export track1_name="${track1_name}"
export track1_type="${track1_type}"
export track1_appid="${track1_appid}"
export track1_apptype="${track1_apptype}"
EOF
        chmod +x export-vars.sh
        echo "✅ export-vars.sh created"

  - task: Bash@3
    name: MakeMainScriptExecutable
    displayName: "📜 Make create-multi-env-vgs.sh executable"
    inputs:
      targetType: 'inline'
      script: |
        chmod +x ./create-multi-env-vgs.sh

  - task: Bash@3
    name: CreateVariableGroups
    displayName: "🚀 Create Env Variable Groups"
    inputs:
      targetType: 'inline'
      script: |
        source ./export-vars.sh

        ENVIRONMENTS="${{ join(',', parameters.environments) }}"
        IFS=',' read -ra ENV_LIST <<< "$ENVIRONMENTS"

        echo "TRACKCOUNT: $TRACKCOUNT"
        echo "Track 1 - Name: $track1_name, Type: $track1_type, AppId: $track1_appid, AppType: $track1_apptype"

        for env in "${ENV_LIST[@]}"; do
          echo "➡️ Creating variable group for $env - $track1_appid - $track1_name"
          ./create-multi-env-vgs.sh "$env" "$track1_appid" "$track1_name" "$track1_type" "$track1_apptype"
        done
