trigger: none

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

steps:
  - script: |
      chmod +x ./generate-export-vars.sh
      ./generate-export-vars.sh
    displayName: '🔧 Generate dynamic export-vars.sh'

  - script: |
      source ./export-vars.sh

      echo "🔁 Environments to process: ${{ join(',', parameters.environments) }}"

      IFS=',' read -ra ENV_LIST <<< "${{ join(',', parameters.environments) }}"

      for ((i=1; i<=TRACKCOUNT; i++)); do
        trackname=$(eval echo "\$track${i}_name")
        tracktype=$(eval echo "\$track${i}_type")
        appid=$(eval echo "\$track${i}_appid")
        apptype=$(eval echo "\$track${i}_apptype")

        echo "🧩 Track $i: name=$trackname, type=$tracktype, appid=$appid, apptype=$apptype"

        for env in "${ENV_LIST[@]}"; do
          echo "➡️ Creating variable group for $env - $appid - $trackname"
          ./create-multi-env-vgs.sh "$env" "$appid" "$trackname" "$tracktype" "$apptype"
        done
      done
    displayName: '🚀 Create Env-specific Variable Groups from Tracks'
