trigger: none

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

steps:
  - checkout: self

  - task: Bash@3
    displayName: 'Make scripts executable'
    inputs:
      targetType: inline
      script: |
        chmod +x ./process-vg-create-vg-source.sh
        chmod +x ./create-multi-env-vgs.sh

  - task: Bash@3
    displayName: 'Generate export-vars.sh from pipeline variables'
    name: exportTrackVars
    inputs:
      targetType: inline
      script: |
        echo "📦 Generating export-vars.sh from defined variables"
        > export-vars.sh

        for i in $(seq 1 50); do
          for key in name type appid apptype; do
            varName="track${i}_${key}"
            value="$(eval echo "\$$varName")"
            if [[ -n "$value" ]]; then
              echo "export $varName=\"$value\"" >> export-vars.sh
            fi
          done
        done

        echo "export TRACKCOUNT=$(TRACKCOUNT)" >> export-vars.sh
        echo "✅ Contents of export-vars.sh:"
        cat export-vars.sh

  - task: Bash@3
    displayName: 'Run Multi-Env Variable Group Creation'
    inputs:
      targetType: filePath
      filePath: ./process-vg-create-vg-source.sh
      arguments: ${{ join(',', parameters.environments) }}
    env:
      ORG: $(ORG)
      PROJECT: $(PROJECT)
      AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)
