trigger: none

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

steps:
  - checkout: self

  - task: Bash@3
    displayName: 'Make scripts executable'
    inputs:
      targetType: inline
      script: |
        chmod +x ./process-vg-create-vg-source.sh
        chmod +x ./create-multi-env-vgs.sh

  - task: Bash@3
    displayName: 'Create Env-specific Variable Groups'
    inputs:
      targetType: filePath
      filePath: ./process-vg-create-vg-source.sh
    env:
      PARAM_ENVIRONMENTS: ${{ join(',', parameters.environments) }}
      ORG: $(ORG)
      PROJECT: $(PROJECT)
      AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)
      TRACKCOUNT: $(trackcount)

      # Flat export: all track variables are automatically exposed
      # For example: track1_name, track2_name, etc.
      # No hardcoding required here – process script will loop over them
