trigger: none

parameters:
  - name: environments
    type: object
    default: ['DEV', 'SIT', 'UAT', 'PT', 'PROD', 'DR']

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  - group: vg-create-vg-source
  - group: devops-secrets-vg

steps:
  - script: |
      echo "🔧 Generating export-vars.sh..."

      echo '#!/bin/bash' > export-vars.sh
      echo "export ORG=\"$(ORG)\"" >> export-vars.sh
      echo "export PROJECT=\"$(PROJECT)\"" >> export-vars.sh
      echo "export AZURE_DEVOPS_PAT=\"$(AZURE_DEVOPS_PAT)\"" >> export-vars.sh
      echo "export TRACKCOUNT=$(TRACKCOUNT)" >> export-vars.sh

      echo "" >> export-vars.sh
      echo "# Dynamically export all trackN_* variables" >> export-vars.sh

      count=$(TRACKCOUNT)
      for i in $(seq 1 $count); do
        for field in name type appid apptype; do
          varname="track${i}_${field}"
          value="$(echo ${{ variables[varname] }})"
          echo "export ${varname}=\"${value}\"" >> export-vars.sh
        done
      done

      chmod +x export-vars.sh
      echo "✅ export-vars.sh created with:"
      cat export-vars.sh
    displayName: '🔧 Dynamically Generate export-vars.sh'

  - script: |
      chmod +x export-vars.sh
      source ./export-vars.sh

      chmod +x ./process-vg-create-vg-source.sh
      ./process-vg-create-vg-source.sh "${{ join(',', parameters.environments) }}"
    displayName: '🚀 Create Env-Specific Variable Groups'
