trigger: none   # manual run

pool:
  name: AKS
  vmImage: 'ubuntu-latest'   # can change to ubuntu-latest if needed

steps:
  - script: |
      echo "Checking if Python is installed..."
      python --version || echo "Python not found"
    displayName: "Check Python availability"

  - script: |
      echo "Installing Python if not present..."
      if ! command -v python &> /dev/null
      then
        echo "Python not installed. Installing now..."
        # On Windows:
        choco install -y python
        # On Linux (uncomment if pool is ubuntu):
        # sudo apt-get update && sudo apt-get install -y python3
      else
        echo "Python already installed"
      fi
    displayName: "Install Python if missing"

  - script: |
      echo "Final check: Python version"
      python --version
    displayName: "Verify Python installation"
