trigger: none   # Run manually

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Checking Python and Pip"
      python3 --version || python --version
      pip3 --version || pip --version
    displayName: "Check Python & Pip"

  - script: |
      echo "Installing requests"
      python3 -m pip install --upgrade pip
      python3 -m pip install requests
    displayName: "Install requests package"

  - script: |
      echo "Verifying requests"
      python3 -m pip show requests
    displayName: "Verify requests installation"
