trigger: none   # Run manually

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Checking Python..."
      python3 --version

      echo "Installing pip if missing..."
       apt-get update
       apt-get install -y python3-pip
    displayName: "Ensure Python & Pip"

  - script: |
      pip3 install requests
    displayName: "Install requests package"

  - script: |
      python3 -m pip show requests
    displayName: "Verify requests installation"
