trigger: none

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Checking Python"
      python3 --version

      echo "Installing pip (official get-pip.py)..."
      curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      python3 get-pip.py --user

      echo "Updating PATH so pip is available"
      export PATH=$PATH:~/.local/bin

      echo "Verify pip"
      pip --version
    displayName: "Ensure Python & Pip"

  - script: |
      echo "Installing requests"
      python3 -m pip install --user requests
    displayName: "Install requests package"

  - script: |
      echo "Verifying requests"
      python3 -m pip show requests
    displayName: "Verify requests installation"
