trigger: none

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Checking Python"
      python3 --version

      echo "Bootstrapping pip (if missing)..."
      python3 -m ensurepip --upgrade || true
      python3 -m pip install --upgrade pip
    displayName: "Ensure Python & Pip"

  - script: |
      echo "Installing requests"
      python3 -m pip install requests
    displayName: "Install requests package"

  - script: |
      echo "Verifying requests"
      python3 -m pip show requests
    displayName: "Verify requests installation"
