trigger: none   # Run manually

pool:
  name: AKS
  vmImage: 'ubuntu-latest'   # or windows-latest

steps:
  - script: |
      python3 --version
      pip3 --version
    displayName: "Check Python & Pip"

  - script: |
      pip3 install requests
    displayName: "Install requests package"

  - script: |
      python3 -m pip show requests
    displayName: "Verify requests installation"
