trigger: none   # Run manually

pool:
  name: AKS
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: "Set up Python 3.x"

  - script: |
      python --version
      pip --version
    displayName: "Check Python & Pip"

  - script: |
      pip install requests
    displayName: "Install requests package"

  - script: |
      python -m pip show requests
    displayName: "Verify requests installation"
