trigger: none   # Run manually

pool:
  name: AKS
  vmImage: 'ubuntu-latest'   # or windows-latest

steps:
  - script: |
      python --version
      pip --version
    displayName: "Check Python & Pip"

  - script: |
      pip install requests
    displayName: "Install requests package"

  - script: |
      python -m pip show requests
    displayName: "Verify requests installation"
